insert into mini_stock (ticker, name)values('FIT', 'Fitbit Inc'); 
insert into mini_stock (ticker, name)values('BOX', 'Box Inc');
insert into mini_stock (ticker, name)values('FB', 'Facebook Inc');
insert into mini_stock (ticker, name)values('AAPL', 'Apple Inc');
insert into mini_stock (ticker, name)values('NFLX', 'Netflix');
insert into mini_stock (ticker, name)values('LNKD', 'LinkedIn Corporation');
insert into mini_stock (ticker, name)values('TSLA', 'Tesla Motors Inc');
insert into mini_stock (ticker, name)values('AMZN', 'Amazon.com, Inc');
insert into mini_stock (ticker, name)values('MSFT', 'Microsoft Corporation');
insert into mini_stock (ticker, name)values('P', 'Pandora Media Inc');
insert into mini_stock (ticker, name)values('AWAY', 'HomeAway');
insert into mini_stock (ticker, name)values('GOOG', 'Alphabet Inc Class C');
insert into mini_stock (ticker, name)values('BABA', 'Alibaba Group');
insert into mini_stock (ticker, name)values('YOKU', 'Youku Tudou');
insert into mini_stock (ticker, name)values('DIS', 'Disney Co');
insert into mini_stock (ticker, name)values('SBUX', 'Starbucks Corporation');
insert into mini_stock (ticker, name)values('NVDA', 'NVIDIA Corporation');
insert into mini_stock (ticker, name)values('EA', 'Electronic Arts Inc');
insert into mini_stock (ticker, name)values('ATVI', 'Activision Blizzard, Inc');
insert into mini_stock (ticker, name)values('QCOM', 'QUALCOMM. Inc');
insert into mini_stock (ticker, name)values('YHOO', 'Yahoo! Inc');
insert into mini_stock (ticker, name)values('ORCL', 'Oracle Corporation');
insert into mini_stock (ticker, name)values('BIDU', 'Baidu Inc');
insert into mini_stock (ticker, name)values('QIHU', 'Qihoo 360 Technology Co Ltd');
insert into mini_stock (ticker, name)values('CVX', 'Chevron');
insert into mini_stock (ticker, name)values('BA', 'Boeing');
insert into mini_stock (ticker, name)values('SNE', 'Sony Corporation');
insert into mini_stock (ticker, name)values('TTWO', 'Take-Two Interactive Software, Inc');
insert into mini_stock (ticker, name)values('NKE', 'Nike Inc');
insert into mini_stock (ticker, name)values('JMEI', 'Jumei International Holding Ltd');
insert into mini_stock (ticker, name)values('YELP', 'Yelp Inc');
insert into mini_stock (ticker, name)values('JWN', 'Nordstrom, Inc');
insert into mini_stock (ticker, name)values('QUNR', 'Qunar Cayman Islands Ltd');
insert into mini_stock (ticker, name)values('NTES', 'NetEase Inc');
insert into mini_stock (ticker, name)values('SINA', 'SINA Corp');
insert into mini_stock (ticker, name)values('CTRP', 'Ctrip.com International, Ltd');
insert into mini_stock (ticker, name)values('UNH', 'UnitedHealth Group Inc');